run-name: learning GitHub Actions
on: [pull_request]
jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
      - name: Run lint for all commits
        run: |
          for commit in $(git log --oneline | awk '{print $1;}'); do
              git checkout $commit
              FOR_LINTER="${commit}"

              echo "the commit hash is ${commit} and ${FOR_LINTER}"
          done
