run-name: learning GitHub Actions
on: [pull_request]
jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
      - name: Run lint for all commits
        run: |
          for commit in $(git ll | awk '{print $1;}'); do
              git checkout $commit
              echo "the commit hash is ${commit}"
          done
